version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20  # Adjust to the version of Node.js used by your project
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the project...
      - npm run build  # This will generate the `out/` directory, adjust if necessary
  post_build:
    commands:
      - echo Syncing build to S3...
      - aws s3 sync out/ s3://${S3_BUCKET_NAME}/ --delete  # Sync the `out/` folder to your S3 bucket
artifacts:
  files:
    - '**/*'  # Include all files (or just the specific ones from `out/` like 'out/**/*')
  base-directory: out  # This is where your build artifacts are located after running `npm run build`
  

